---
# 3 dashes above denote YAML file
 
name: Checks

on: [push]

jobs: 
  # id of the job
  test-lint:
    name: Test and lint
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        # Runs the django buit-in testing suite
        run: docker compose run --rm app sh -c "python manage.py test"
      - name: lint
        # Runs the flake8 linter
        run: docker compose run --rm app sh -c "flake8"